name: iOS starter workflow
permissions:
  contents: read

on:
  push:
    branches: [ "release/*", "feature/*", "hotfix/*" ]
  pull_request:
    branches: [ "master", "develop", "release/*" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=$(xcrun simctl list devices available -j | ruby -rjson -e '
            devices = JSON.parse(STDIN.read).fetch("devices").values.flatten
            device = devices.find { |candidate| candidate["isAvailable"] && candidate["name"].start_with?("iPhone") }
            abort "No available iPhone simulator" unless device
            puts device.fetch("udid")
          ')
          if [ "$scheme" = default ]; then scheme=$(cat default); fi
          if ls -A | grep -qi '\.xcworkspace$'; then filetype_parameter="workspace" && file_to_build=$(ls -A | grep -i '\.xcworkspace$'); else filetype_parameter="project" && file_to_build=$(ls -A | grep -i '\.xcodeproj$'); fi
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,id=$device"
      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=$(xcrun simctl list devices available -j | ruby -rjson -e '
            devices = JSON.parse(STDIN.read).fetch("devices").values.flatten
            device = devices.find { |candidate| candidate["isAvailable"] && candidate["name"].start_with?("iPhone") }
            abort "No available iPhone simulator" unless device
            puts device.fetch("udid")
          ')
          if [ "$scheme" = default ]; then scheme=$(cat default); fi
          if ls -A | grep -qi '\.xcworkspace$'; then filetype_parameter="workspace" && file_to_build=$(ls -A | grep -i '\.xcworkspace$'); else filetype_parameter="project" && file_to_build=$(ls -A | grep -i '\.xcodeproj$'); fi
          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,id=$device"
